### ISSUE TITLE
Start with some tasks not running

### ISSUE THREAD

**Issue by Janiczek** [lydell/run-pty#32]
For my usecase of `run-pty`:
```bash
run-pty \
  % yarn watch \
  % ../dev/start staging --no-build --no-open \
  % ./watch-compile.sh \
  % yarn review --watch \
  % yarn spec --parallel --watch \
  % yarn test --watch
```
it would be useful to me if I could start `run-pty` with some of these tasks disabled.
Eg. I only run the last three: review, specs and tests at the late end of a feature development cycle.

So currently I run the above invocation and immediately go to the bottom three items in the dashboard to kill them.

I guess an easy workaround would be to have two `run-pty` invocations: one with the first three processes and one with all six.
But still, perhaps this will be useful to you for future feature considerations.

**Comment by lydell** [comment]
I guess you could create a script called `wait.bash`:

```bash
#!/usr/bin/env bash
read -p "Press any key to start"
"$@"
```

And then change to for example `% ./wait.bash yarn review --watch`.

The ones using `./wait.bash` would still be marked as 🟢 running though (because they are), but if that’s unwanted you could swap out the emoji using the [config file](https://github.com/lydell/run-pty#advanced-mode).

I haven’t bumped into this use case myself (so far?), so I’m a bit reluctant to add it (don’t want to it to become too complex eventually), but at the same time it _sounds_ somewhat easy to do: We could have a flag in the config file for this, and the `run-pty --auto-exit` mode already has the concept of waiting commands.

**Comment by lydell** [comment]
One thing I just thought of:

1. You start run-pty, with some tasks not running.
2. After some time, you decide to start them.
3. Don’t you go back to 1 again some time? How do you do that? Kill everything and restart? There’s something that feels off to me with this – the feature feels half-made somehow.

**Comment by Janiczek** [comment]
Honestly, I've forgotten about this issue after creating multiple pty scripts: one I call most of the time and one I call only sometimes. Feel free to close this!
